/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ProfessorBean;
import dao.ProfessorDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form LoginProf
     */
    public CadastroProfessor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        escola_pertencente = new javax.swing.JTextField();
        disciplina = new javax.swing.JComboBox<>();
        confirmar_senha = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        nome.setBorder(null);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(170, 230, 150, 16);

        telefone.setBorder(null);
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(telefone);
        telefone.setBounds(170, 370, 140, 20);

        escola_pertencente.setBorder(null);
        getContentPane().add(escola_pertencente);
        escola_pertencente.setBounds(160, 430, 390, 20);

        disciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Matemática", "Biologia", "Física", "Química", "Ed. Física", "Inglês", "Espanhol", "Geografia", "Filosofia", "Sociologia", "História" }));
        getContentPane().add(disciplina);
        disciplina.setBounds(450, 370, 130, 22);

        confirmar_senha.setBorder(null);
        getContentPane().add(confirmar_senha);
        confirmar_senha.setBounds(460, 300, 130, 16);

        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(170, 300, 160, 20);

        senha.setBorder(null);
        getContentPane().add(senha);
        senha.setBounds(440, 230, 150, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/StyleCadastroProfessor.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 670, 616);

        editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editar.setText("EDITAR DADOS");
        editar.setBorderPainted(false);
        editar.setContentAreaFilled(false);
        editar.setDefaultCapable(false);
        editar.setFocusPainted(false);
        editar.setFocusable(false);
        editar.setRequestFocusEnabled(false);
        editar.setRolloverEnabled(false);
        editar.setVerifyInputWhenFocusTarget(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(350, 510, 170, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CADASTRAR DADOS");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.setVerifyInputWhenFocusTarget(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 510, 190, 50);

        jButton3.setText("jButton3");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverEnabled(false);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(10, 174, 79, 40);

        setSize(new java.awt.Dimension(654, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //Validar Email
        int v = 0;
        
        for(int i = 0; i < email.getText().length();i++){
            if(email.getText().charAt(i) == '@' && email.getText().endsWith("@gmail.com")){
                v = v + 1;
            }
        }
        
        
        if(v == 1){
            
        
            if(email.getText().equals("") 
                || String.valueOf(senha.getPassword()).equals("")
                || nome.getText().equals("")
                || String.valueOf(disciplina.getSelectedItem()).equals("")
                || escola_pertencente.getText().equals("")
                || String.valueOf(confirmar_senha.getPassword()).equals("")
            )
            {
                JOptionPane.showMessageDialog(null,"Preencha todos os campos");
            }else if(!(String.valueOf(confirmar_senha.getPassword()).equals(String.valueOf(senha.getPassword())))){
                JOptionPane.showMessageDialog(null,"Campos não Coincidem","AVISO",JOptionPane.ERROR_MESSAGE);
            }else{

                ProfessorBean pb = new ProfessorBean();
                ProfessorDao  pd = new ProfessorDao();

                pb.setNome(nome.getText());
                pb.setEmail(email.getText());
                pb.setSenha(String.valueOf(senha.getPassword()));
                pb.setTelefone(telefone.getText());
                pb.setEscola_pertencente(escola_pertencente.getText());
                pb.setDisciplina(String.valueOf(disciplina.getSelectedItem()));

                pd.create(pb);
                
                nome.setText("");
                email.setText("");
                telefone.setText("");
                escola_pertencente.setText("");
                disciplina.setSelectedIndex(0);
                senha.setText("");
                confirmar_senha.setText("");
            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Email Inválido","AVISO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        
        //Validar Email
        int v = 0;
        
        for(int i = 0; i < email.getText().length();i++){
            if(email.getText().charAt(i) == '@' && email.getText().endsWith("@gmail.com")){
                v = v + 1;
            }
        }
        
        if(v == 1){
        
            if(email.getText().equals("") 
                    
                || String.valueOf(senha.getPassword()).equals("")
                || nome.getText().equals("")
                || String.valueOf(disciplina.getSelectedItem()).equals("")
                || escola_pertencente.getText().equals("")
                || String.valueOf(confirmar_senha.getPassword()).equals("")        
                    
            )
            {
                JOptionPane.showMessageDialog(null,"Preencha todos os campos");
            }else if(!(String.valueOf(confirmar_senha.getPassword()).equals(String.valueOf(senha.getPassword())))){
                JOptionPane.showMessageDialog(null,"Campos não Coincidem");
            }else{

                ProfessorBean pb = new ProfessorBean();
                ProfessorDao  pd = new ProfessorDao();

                String email = JOptionPane.showInputDialog("Digite seu antigo Email: ");

                pb.setNome(nome.getText());
                pb.setEmail(this.email.getText());
                pb.setSenha(String.valueOf(senha.getPassword()));
                pb.setTelefone(telefone.getText());
                pb.setEscola_pertencente(escola_pertencente.getText());
                pb.setDisciplina(String.valueOf(disciplina.getSelectedItem()));
                pb.setSenha(String.valueOf(senha.getPassword()));

                pd.atualizar(pb,email);
                
                nome.setText(pb.getNome());
                this.email.setText(pb.getEmail());
                senha.setText(pb.getSenha());
                telefone.setText(pb.getTelefone());
                escola_pertencente.setText(pb.getEscola_pertencente());
                senha.setText(pb.getSenha());
            }
        
        }else{
            JOptionPane.showMessageDialog(null,"Email Inválido","AVISO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmar_senha;
    private javax.swing.JComboBox<String> disciplina;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField escola_pertencente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField telefone;
    // End of variables declaration//GEN-END:variables
}
